### ISSUE TITLE
blockTemplate.js is missing position variable in serializeHeader function

### ISSUE THREAD

**Issue by Longlius** [foxer666/node-stratum-pool#11]
Line 89 of blockTemplate.js begins the definition of the serializeHeader function, which uses the variable 'position'. However this is undefined. I believe it should be initialized to 0.

Code throws an exception without ```var position = 0;``` added.

**Comment by devnull-ed** [comment]
Duplicate
https://github.com/foxer666/node-open-mining-portal/issues/40
