### ISSUE TITLE
groestlmyriad algorithm, block rejected for digibyte coin.

### ISSUE THREAD

**Issue by trustethorg** [foxer666/node-stratum-pool#19]
@foxer666 
https://github.com/zone117x/node-stratum-pool/issues/140

i've tested groestlmyriad algorithm on digibyte
it is similar as your code.
you also need to test result on such algorithm.

Do you have a solution , prevent block rejection?

thanks.

**Comment by trustfarm-dev** [comment]
@devnull-ed  thanks for the informations.
it was same problem introduced several times,
but, there's cannot found, finally confirmed solutions and reference codes.

my coin config was 

coins/digibyte.groestl.conf

{
    "name": "digibyte-groestl",
    "symbol": "DGB",
    "algorithm": "groestlmyriad"
}

and coindaemon configs are followings::

**Comment by devnull-ed** [comment]
Is https://github.com/foxer666/node-stratum-pool/issues/20 issue solves your question?

**Comment by trustfarm-dev** [comment]
Good informations .
I will do above mention.
Needs a verify time. I didn't found testnet.
So live test will needs.
If there's result I will inform you.
Thank.

**Comment by devnull-ed** [comment]
Thank you. Closing in favor of https://github.com/foxer666/node-stratum-pool/issues/20
