### ISSUE TITLE
Algo-specific code in header hashing (possibly break some coins)

### ISSUE THREAD

**Issue by devnull-ed** [foxer666/node-stratum-pool#20]
Some coins hash their blockheader with classic sha256d instead of their own proof-of-work algo. Although block is accepted by the network consensus, node-stratum-server generates invalid hash for this block (because coin-daemon accept raw source data which node then transorm into valid hash). And then tries to find the block by incorrect hash which obviously lead to "Block not found" error.
To make node-stratum server correctly set up environment, these checks should be coin-related rather than algo-specific code.
In jobManager we have this code:
![image](https://user-images.githubusercontent.com/35138264/37930042-c4583e28-316b-11e8-8d66-18e262bc4427.png)
This means that node-stratum-server will hash block with sha256D any neoscrypt coin nevertheless what sha256dheader flag coin have. 

The solution is remove algo-specific checks and leave only sha256DHeader check. This will break some coins but instead we will have more stable code. This will require more testing as well to correct broken coins (edit coin-configs for correct sha256D flag).

**Comment by trustfarm-dev** [comment]
Good Informations
